### ISSUE TITLE
In-memory decryption?

### ISSUE THREAD

**Issue by akx** [nrosvall/ylva#1]
As e.g. [this HN comment](https://news.ycombinator.com/item?id=19835832) points out, as well as [this code](https://github.com/nrosvall/ylva/blob/2a4afcfb3727151fa09fdd7fa4bd58954b457dd6/Ylva/MainWindow.cs#L134-L137), Ylva seems to decrypt the "vault" onto disk to read from it.

This feels like a fairly insecure design – would it not be better to decrypt the data from disk on-demand into memory in StorageManager (and similarly only write encrypted data when it's time to [`Preserve()`](https://github.com/nrosvall/ylva/blob/2a4afcfb3727151fa09fdd7fa4bd58954b457dd6/Ylva/StorageManager.cs#L105) things?

**Comment by nrosvall** [comment]
Hi,

Actually I'm working on this at the moment. There will be some other security related changes too. :)

**Comment by nrosvall** [comment]
Now by default, Ylva does not keep decrypted data on disk. There's an option available to keep the decrypted data on disk, but by default it's off.
