### ISSUE TITLE
Manual > auto-encrypt flag use

### ISSUE THREAD

**Issue by nh3oh** [nrosvall/ylva#12]
Dear Dev,
Should be kind from you to tell us little more about using --auto-encrypt flag.

Might be I'm dum, but I didn't manage to use it.

Thanks for this nice tool.

Best regards.

**Comment by nrosvall** [comment]
Hi!

It's quite naive how it works at the moment. I'm planning to change the behavior, but it's more complicated to implement than I thought.

At the moment: 
Say you have a decrypted pw database and you want to find something in it.
You can run ylva --auto-encrypt --find "something"

That would then automatically encrypt the database after the search. It will prompt for the password to use in encryption.

**Comment by nh3oh** [comment]
Thanks a lot for answering so quickly :))

Shame on me, I didn't think.. this way :((

I'm pretty new password manager user but I enjoy so much such "KISS" piece of software !

Great shot !
