### ISSUE TITLE
[Enhancement] Multiline Notes

### ISSUE THREAD

**Issue by dehnli** [nrosvall/ylva#2]
As I can notice current release has no multiline Notes. Is it possible to implement it?

**Comment by nrosvall** [comment]
Hi, Sorry it took so long to answer, Github did not notify me about the issue at all.

Hmm, yes it should be possible. I will implement it for the next release (sometime in January, I'm quite busy at the moment).

Thanks!

**Comment by nrosvall** [comment]
Unfortunately this would add too much complexity so I don't see this as necessary change.
