### ISSUE TITLE
Invalid password or tampered data. Aborted

### ISSUE THREAD

**Issue by mattwr18** [nrosvall/ylva#5]
hey @nrosvall thanks for this amazing password manager for cli.
I am getting this error :point_up_2: 
This is the second time this has happened to me, the first went away after I turned `CapsLock` on and off, surprisingly. This time, I can't seem to get anything to work.
 I choose the same password every time, so I'm pretty certain it's not this. Is there anything I can do?

**Comment by mattwr18** [comment]
Sorry, somehow I mis-typed the password twice :man_facepalming:

**Comment by nrosvall** [comment]
Hi!

No worries, I thought it might be some mis-typing. Thanks for using Ylva!
