### ISSUE TITLE
Where is <qrcodegen/qrcodegen.h>?

### ISSUE THREAD

**Issue by stefanhusmann** [nrosvall/ylva#9]
The file qr.c wants to include <qrcodegen/qrcodegen.h>, but where can I get this file from? I guess I miss a dependency.

**Comment by stefanhusmann** [comment]
This one?

https://github.com/nayuki/QR-Code-generator/archive/v1.6.0.tar.gz

**Comment by nrosvall** [comment]
Hi. Yes that one. Should be in the repositories of most distributions too. On Fedora libqrcodegen-devel.

**Comment by stefanhusmann** [comment]
Okay, on Arch Linux it is only available in AUR, not as an official package.

**Comment by nrosvall** [comment]
Ok! Good to know! I will make the feature optional, so that Ylva can be compiled without QR code support.
